site_name: Zombie Brain
site_url: 
site_dir: public

theme:
  name: material
  palette:
    scheme: default

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
        permalink: true

plugins:
  - search
  - roamlinks
  - callouts
  - tags:
      tags_file: Tags.md
